# Assignment: Numpy
By Stefan Amoah ABabio

Perform the follwing tasks:


In [2]:
#1: import the numpy library
import numpy as np

In [6]:
#2: create a random 10x10 array named A
a = np.random.randint(10, size=(10, 10))
print(a)


[[4 1 3 4 7 5 1 8 3 6]
 [1 1 8 3 2 8 3 0 9 3]
 [8 1 9 5 0 3 2 0 0 9]
 [6 2 5 6 0 7 4 6 3 3]
 [4 5 0 7 3 1 8 1 6 4]
 [8 8 5 5 8 3 1 1 5 0]
 [8 8 5 8 0 1 2 4 9 9]
 [7 2 1 6 5 8 7 0 0 5]
 [3 9 9 9 4 1 3 2 9 7]
 [0 5 5 3 3 7 3 0 9 7]]


In [7]:
#3: return only the odd rows of A
oddRows = a[a % 2 ==1]
print(oddRows)

[1 3 7 5 1 3 1 1 3 3 9 3 1 9 5 3 9 5 7 3 3 5 7 3 1 1 5 5 3 1 1 5 5 1 9 9 7
 1 5 7 5 3 9 9 9 1 3 9 7 5 5 3 3 7 3 9 7]


In [8]:
#4: perform a matrix multiplication of A with it's transposed
b = a.transpose()
print(b)


[[4 1 8 6 4 8 8 7 3 0]
 [1 1 1 2 5 8 8 2 9 5]
 [3 8 9 5 0 5 5 1 9 5]
 [4 3 5 6 7 5 8 6 9 3]
 [7 2 0 0 3 8 0 5 4 3]
 [5 8 3 7 1 3 1 8 1 7]
 [1 3 2 4 8 1 2 7 3 3]
 [8 0 0 6 1 1 4 0 2 0]
 [3 9 0 3 6 5 9 0 9 9]
 [6 3 9 3 4 0 9 5 7 7]]


In [10]:
#5: compute the matrix inverse of A
inverse = np.linalg.inv(a)
print(inverse)


[[-0.00204627  0.02673062  0.0580512  -0.01349901  0.05016307  0.07404453
   0.05750541 -0.03853076 -0.12843251 -0.02519966]
 [-0.07202324 -0.21663496  0.03344946  0.13879319  0.02407166  0.08633096
  -0.08731435 -0.09392412 -0.00885921  0.22654245]
 [-0.00809802 -0.03160776  0.11995779  0.07834093  0.07016824  0.05134038
  -0.13507602 -0.14239955  0.00676702  0.0612012 ]
 [-0.01114568  0.19428906 -0.22178693 -0.12973027 -0.24937016 -0.1634039
   0.18905039  0.34415716  0.26205977 -0.34141385]
 [ 0.07845326  0.02546931  0.00441443 -0.09001274  0.02291583  0.03469465
  -0.04428196  0.01465174  0.01598385 -0.02787008]
 [-0.03242968  0.01366467 -0.07763658  0.03745925 -0.12981203 -0.02093232
   0.03771526  0.12078971  0.01728261  0.02783136]
 [-0.01258194 -0.12256259  0.15484748  0.13215119  0.27658835  0.06402873
  -0.20169468 -0.21781249 -0.113045    0.1774821 ]
 [ 0.06023329 -0.09821833  0.03635252  0.13255522  0.08349207  0.02365792
  -0.07334178 -0.14698471 -0.04549025  0.08398285]
 

In [11]:
#6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
if a.any() > 0.5:
    larger1 = a
    larger2 = larger1 / 2
    print(larger2)

[[2.  0.5 1.5 2.  3.5 2.5 0.5 4.  1.5 3. ]
 [0.5 0.5 4.  1.5 1.  4.  1.5 0.  4.5 1.5]
 [4.  0.5 4.5 2.5 0.  1.5 1.  0.  0.  4.5]
 [3.  1.  2.5 3.  0.  3.5 2.  3.  1.5 1.5]
 [2.  2.5 0.  3.5 1.5 0.5 4.  0.5 3.  2. ]
 [4.  4.  2.5 2.5 4.  1.5 0.5 0.5 2.5 0. ]
 [4.  4.  2.5 4.  0.  0.5 1.  2.  4.5 4.5]
 [3.5 1.  0.5 3.  2.5 4.  3.5 0.  0.  2.5]
 [1.5 4.5 4.5 4.5 2.  0.5 1.5 1.  4.5 3.5]
 [0.  2.5 2.5 1.5 1.5 3.5 1.5 0.  4.5 3.5]]


In [12]:
#7: compute the singular value decomposition of A
#7.1: plot the singular values
#7.2: reconstruct A' by using only the top 5 singular values

w,y,z = np.linalg.svd(a, full_matrices=True)
w.shape, y.shape, z.shape

((10, 10), (10,), (10, 10))